version: "3.0"

services:
  trojan:
    build:
      context: trojan
      args:
        TROJAN_SERVER_HOST: ${TROJAN_SERVER_HOST}
        TROJAN_SERVER_PORT: ${TROJAN_SERVER_PORT}
        TROJAN_PASSWORD: ${TROJAN_PASSWORD}
    container_name: trojan
    ports:
      - "1080:1080"
    networks:
      - proxynet
    restart: always
  privoxy:
    build:
      context: privoxy
    container_name: privoxy
    ports:
      - "1081:1081"
    volumes:
      - ./privoxy/config:/etc/privoxy/config:ro
    depends_on:
      - trojan
    networks:
      - proxynet
    restart: always
  aria2:
    build:
      context: aria2
    container_name: aria2
    ports:
      - "6800:6800"
    volumes:
      - downloads:/data/downloads
    restart: always
  webui-aria2:
    build:
      context: webui-aria2
    container_name: webui-aria2
    ports:
      - "9100:80"
    depends_on:
      - aria2
    restart: always
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "9200:80"
    depends_on:
      - aria2
    volumes:
      - downloads:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: always

volumes:
  downloads:

networks:
  proxynet:
    driver: bridge

